### PR TITLE
Rue89 analytics features

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This branch contains the following WIP pull requests:
- [Display Basic Course Information on Course Home Page](https://github.com/edx/edx-analytics-dashboard/pull/334)
- [Optional feature to show engagement as percent of enrollment](https://github.com/edx/edx-analytics-dashboard/pull/335)
- [User Profiles](https://github.com/edx/edx-analytics-dashboard/pull/338)
- [Typology](https://github.com/edx/edx-analytics-dashboard/pull/344)
- [Problem history for a single user and course](https://github.com/edx/edx-analytics-dashboard/pull/343)

All tests are passing.

### CODE REVIEW

**Comment by smarnach** [comment]
@bradenmacdonald What is the rationale for including the first three commits?  Didn't you use current master as a basis for merging anyway?

**Comment by bradenmacdonald** [comment]
@smarnach I'm honestly not sure why those three commits appeared. I didn't use the current master but a slightly older version (`open-craft/master`). When I look at the branch locally, those commits are not present. I think it's a bug in GitHub and they're only showing because I moved `master` forward after opening this PR.

**Comment by smarnach** [comment]
We need to keep in mind that we will have to include the commit hash of the data-api-client here once that PR is merged.  (This comment is just to have a note about it somewhere.)

**Comment by smarnach** [comment]
@bradenmacdonald Ah, right, I think Github remembers the state of the base branch at the moment you create the PR, and will use that commit to determine the list of commits.  I noticed that before.

I also dislike that it simply lists the commits in the order of their timestamps instead of their topological order in the commit graph.

**Comment by smarnach** [comment]
I can't see the "Posted in Forum" and "Active (%)" columns on the engagement page.  This is probably due to some data lacking, or some settings.  However, I do see a percentage in the "Active students last week" card.

**Comment by smarnach** [comment]
I'm getting a [traceback](https://gist.github.com/smarnach/175da6dbcb2012466b16) when trying to access the user profiles page for my test course.

**Comment by smarnach** [comment]
The typology page is working fine.  I will test the problem history page once we fixed the user profiles page.

**Comment by bradenmacdonald** [comment]
@smarnach Here are some replies:
- Missing "Posted in forum": you need to enable the switch `show_engagement_forum_activity`
- Missing "Active (%)": This was a bug - I have fixed it with edfbec22bc12221465fad1f9cb8b29de5e23e5c2 and I will add that fix into the "upstream" PR as well.
- Traceback: I'm not seeing that same issue. Is it possible that the wrong version of `data-api-client` is active in your insights virtualenv? You can see that the `list_users` method is included in [the merged PR](https://github.com/open-craft/edx-analytics-data-api-client/pull/2/files#diff-9553aea1b749e8bc59b71f7573981bdaR108).

**Comment by bradenmacdonald** [comment]
I have pushed a commit to bump the API client version. (BTW I'm not sure if we're going to merge these PRs or not - we could just treat each `rue89-analytics-features` branch as the release branch for now)

**Comment by smarnach** [comment]
@bradenmacdonald You are right, the API client was on the wrong version.  (What I did was to clone the client into a new directory, change to the rue89-analytics-features branch and ran `pip install .`.  Pip decided to do nothing since the requirement was already satisfied, and I didn't read the output carefully.  `pip install -U .` and `pip install -e .` both would have worked.  The typology page worked since I still happened to be on that branch.)

I tested all new features and your fix again with the right API client version, and everything is working great.  So :+1: on all PRs. :)  (I think I gave an explicit thumbs up on all other PRs already.)

**Comment by mtyaka** [comment]
The changes from this PR were pulled into https://github.com/rue89-tech/edx-analytics-dashboard/tree/rue89

**Pull request closed without merging**
