### PR TITLE
Add client for the Enrollment API and use it to display a list of courses in user profiles.

### PR DESCRIPTION
**Pull request by smarnach**
This adds a list of courses a user is enrolled to to the user profile page added in [upstream PR #338](https://github.com/edx/edx-analytics-dashboard/pull/338).  For testing, follow the instructions there, including the dependencies for the other edx-analytics components
#### Additional dependency
- [edx/edx-platform#9345](https://github.com/edx/edx-platform/pull/9345)

### CODE REVIEW

**Comment by smarnach** [comment]
@mtyaka This is ready for review now.

**Comment by mtyaka** [comment]
@smarnach Looking good! :+1: Would be great if we could start adding some tests for the new functionality.

**Comment by smarnach** [comment]
@braden @tikr I made this PR against the users-navigation branch.  Do you think it can be merged now, so we can get away with fewer upstream PRs?  Or should I merge into master after the other PRs have been merged?

**Comment by smarnach** [comment]
@bradenmacdonald  @itsjeyd I made this PR against the users-navigation branch.  Do you think it can be merged now, so we can get away with fewer upstream PRs?  Or should I merge into master after the other PRs have been merged?

**Comment by bradenmacdonald** [comment]
Up to @itsjeyd since it's his PR :) That makes sense to me though. BTW, as Matjaz mentioned, can you add a test or two for the changes to the view?

**Comment by smarnach** [comment]
@bradenmacdonald As far as I can tell, the view I changed didn't have any tests in the first place, so I can't really test the changes to the view.  I agree that we should have tests, but we should coordinate who is going to test what.  Maybe it's best to get the branches merged and write a test for the new pages once the design has stabilised.

**Comment by smarnach** [comment]
@itsjeyd Thanks for rebasing and merging this for me – highly appreciated!  Looks all good, including the updates to the description of [your PR #338](https://github.com/edx/edx-analytics-dashboard/pull/338).

**Pull request merged**
